<a href="https://colab.research.google.com/github/Stared55/analiza_danych/blob/develop/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

In [69]:

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

data_raw = pd.DataFrame(data=data)
data_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [72]:
df = data_raw.copy()

for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

# df.describe()
# df.describe().T
# df.describe(include=['category']).T


# LabelEncoder
from sklearn.preprocessing import LabelEncoder, StandardScaler

le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

# le.classes_

df = pd.get_dummies(data=df, drop_first=True)

scaler = StandardScaler()
df[['price','weight']] = scaler.fit_transform(df[['price','weight']])

display(df)

print(df['price'].mean())



print(f"{df['price'].std():.4}")

,price,weight,bought,size_M,size_XL,color_green,color_red,gender_male
0,1.845062,1.366002,1,False,True,False,True,False
1,-0.691898,0.623610,0,False,False,True,False,True
2,-0.461266,-1.603567,1,True,False,False,False,True
3,0.230633,-0.415740,0,False,False,True,False,False
4,-0.922531,0.029696,1,True,False,False,True,False

0.0
1.118